FROM node:18.4-buster


# Install packages from apt
RUN apt update && \
    apt install vim -y

WORKDIR /workdir
COPY ./package*.json /workdir/

RUN npm install pm2 -g --verbose
RUN rm -rf node_modules && \
    npm install --verbose
